name: mvae-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - geomstats
  - pip
  - pip:
      - geomstats[opt]
variables:
  GEOMSTATS_BACKEND: numpy

# update environment after changes:
# conda env update --file conda-env.yaml --prune