name: mvae-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - geomstats
  - wandb
  - plotly
  - tqdm
  - pip
  - pip:
      - git+https://github.com/geoopt/geoopt.git
      - torch-topological
variables:
  GEOMSTATS_BACKEND: numpy

# update environment after changes:
# conda env update --file conda-env.yaml --prune